typography_spectrum: 0.03675502282567322
color:
  brandStrength: 0.6242563847918063
  lightness: 0.4371529412455857
  saturation: 0.9690714543685317
  rhythmicContrast: 0.4602037270087749
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.4555117965210229
author:
  name: Michael Ng
  email: michael.ng@cmngcapital.com
  url: www.cmngcapital.com
name: CMNG Capital
navigation:
  - name: About CMNG Capital
    id: 12322eb3-98c4-4ff9-a507-bd27606818c6
    type: content
  - name: Amko SOLARA
    url: 'http://www.amkosolara.com'
    type: external
  - name: Amko SOLARA
    url: 'https://www.facebook.com/amkosolara/'
    type: external
  - name: DataGrid International
    url: 'http://www.datagridinternational.com'
    type: external
  - name: Future Cities 2016
    url: 'https://youtu.be/s0nK279GIjs'
    type: external
title: Infrastructure Investment Fund
description: Investing a Smart City future
