typography_spectrum: 0.03675502282567322
color:
  brandStrength: 0.6242563847918063
  lightness: 0.4371529412455857
  saturation: 0.9690714543685317
  rhythmicContrast: 0.4602037270087749
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.4555117965210229
author:
  name: Michael Ng
  email: michael.ng@cmngcapital.com
  url: www.cmngcapital.com
name: CMNG Capital
navigation:
  - name: Amko SOLARA
    url: 'https://www.facebook.com/amkosolara/'
    type: external
  - name: Amko SOLARA
    url: 'http://www.amkosolara.com'
    type: external
  - name: DataGrid International
    url: 'http://www.datagridinternational.com'
    type: external
  - name: Mapping of bike sharing data will change the way you see these cities
    id: bf06a3e4-d6da-4999-9c9a-0d3c9325a432
    type: content
  - name: Audi's new technology is the beginning of the end of traffic lights
    id: 015eab4e-7744-4c8d-a2f0-cd04ad1434d7
    type: content
  - name: Future Cities
    url: 'https://youtu.be/IhHWijahHak'
    type: external
title: Infrastructure Investment Fund
description: Investing a Smart City future
