typography_spectrum: 0.3379658979829401
color:
  brandStrength: 0.32711215736344457
  lightness: 0.7539672481361777
  saturation: 0.8450265321880579
  rhythmicContrast: 0.854541597655043
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
layout_spectrum: 0.3315722194965929
author:
  name: Michael Ng
  email: michael.ng@cmngcapital.com
  url: www.cmngcapital.com
name: CMNG Capital
navigation:
  - name: About CMNG Capital - Smart City Infrastructure Investments
    id: 12322eb3-98c4-4ff9-a507-bd27606818c6
    type: content
  - name: Future Smart City 2016 (youtube)
    url: 'https://youtu.be/GC4ri7qnJk8'
    type: external
  - name: Using PPPs to fund critical greenfield infrastructure projects (mckinsey)
    url: >-
      http://www.mckinsey.com/industries/public-sector/our-insights/using-ppps-to-fund-critical-greenfield-infrastructure-projects
    type: external
  - name: Our Partners - DataGrid International
    url: 'http://www.datagridinternational.com'
    type: external
  - name: Our Partners - Amko SOLARA
    url: 'http://www.amkosolara.com'
    type: external
title: Infrastructure Investment Fund
description: Investing a Smart City future
