description: Investing a Smart City future
name: CMNG Capital
author:
  name: Michael Ng
  email: michael.ng@cmngcapital.com
  url: www.cmngcapital.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0
title: Infrastructure Investment Fund
color:
  saturation: 0.8450266
  brandStrength: 0.3260261
  rhythmicContrast: 0.6245336
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  lightness: 0.8642724
typography_spectrum: 0
navigation:
  - name: About CMNG Capital - Smart City Infrastructure Investments
    id: 12322eb3-98c4-4ff9-a507-bd27606818c6
    type: content
  - name: Future Smart City 2016 (youtube)
    url: 'https://youtu.be/GC4ri7qnJk8'
    type: external
  - name: Using PPPs to fund critical greenfield infrastructure projects (mckinsey)
    url: >-
      http://www.mckinsey.com/industries/public-sector/our-insights/using-ppps-to-fund-critical-greenfield-infrastructure-projects
    type: external
  - name: Our Partners - DataGrid International
    url: 'http://www.datagridinternational.com'
    type: external
  - name: Our Partners - Amko SOLARA
    url: 'http://www.amkosolara.com'
    type: external
