layout_spectrum: 0.3315722194965929
typography_spectrum: 0.01382032735273242
color:
  brandStrength: 0.11477023526094854
  lightness: 0.1509929383173585
  saturation: 0.30406593275256455
  rhythmicContrast: 0.27741853590123355
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
author:
  name: Michael Ng
  email: michael.ng@cmngcapital.com
  url: www.cmngcapital.com
name: CMNG Capital
navigation:
  - name: About CMNG Capital - Smart City Infrastructure Investments
    id: 12322eb3-98c4-4ff9-a507-bd27606818c6
    type: content
  - name: Future Smart City 2016 (youtube)
    url: 'https://youtu.be/GC4ri7qnJk8'
    type: external
  - name: Using PPPs to fund critical greenfield infrastructure projects (mckinsey)
    url: >-
      http://www.mckinsey.com/industries/public-sector/our-insights/using-ppps-to-fund-critical-greenfield-infrastructure-projects
    type: external
  - name: Our Partners - DataGrid International
    url: 'http://www.datagridinternational.com'
    type: external
  - name: Our Partners - Amko SOLARA
    url: 'http://www.amkosolara.com'
    type: external
title: Infrastructure Investment Fund
description: Investing a Smart City future
