typography_spectrum: 0.16791931400075555
color:
  brandStrength: 0.3043730373028666
  lightness: 0.786222972208634
  saturation: 0.433917197631672
  rhythmicContrast: 0.689049664651975
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
layout_spectrum: 0.3315722194965929
author:
  name: Michael Ng
  email: michael.ng@cmngcapital.com
  url: www.cmngcapital.com
name: CMNG Capital
navigation:
  - name: About CMNG Capital
    id: 12322eb3-98c4-4ff9-a507-bd27606818c6
    type: content
  - name: Future Smart City 2016
    url: 'https://youtu.be/GC4ri7qnJk8'
    type: external
  - name: Our Partners - DataGrid International
    url: 'http://www.datagridinternational.com'
    type: external
  - name: Our Partners - Amko SOLARA
    url: 'http://www.amkosolara.com'
    type: external
title: Infrastructure Investment Fund
description: Investing a Smart City future
