layout_spectrum: 0.4555117965210229
typography_spectrum: 0.03675502282567322
color:
  brandStrength: 0.6242563847918063
  lightness: 0.4371529412455857
  saturation: 0.9690714543685317
  rhythmicContrast: 0.4602037270087749
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
name: CMNG Capital
navigation:
  - name: Amko SOLARA
    url: 'https://www.facebook.com/amkosolara/'
    type: external
  - name: Amko SOLARA
    url: 'http://www.amkosolara.com'
    type: external
  - name: DataGrid International
    url: 'http://www.datagridinternational.com'
    type: external
title: Infrastructure Investment Fund
description: Investing a Smart City future
